### ISSUE TITLE
Drush Makefile

### ISSUE THREAD

**Issue by iamkirkbater** [x-team/vdd#5]
Hi, 

I'm new to Vagrant and Chef.  Where would I put something like a drush makefile that runs as soon as vagrant is up and running?  So, I would do "vagrant up" and then it would start the VM and install drupal like it does, and then run the drush make command, so I can run one command, go get some coffee, talk to some coworkers, etc and come back to a site with all modules downloaded, enabled, themes installed, etc.

Thanks

**Comment by geraldvillorente** [comment]
You need to create a custom recipe that will do the stuff you mentioned. Your script should ensure that Drush is present and all required dependencies are installed.

Check this [page](https://www.chef.io/blog/2011/09/07/guide-to-writing-chef-cookbooks/) and [this](https://www.digitalocean.com/community/tutorials/how-to-create-simple-chef-cookbooks-to-manage-infrastructure-on-ubuntu).
