### ISSUE TITLE
Syntax error in Vagrantfile using Ruby 2.0.0p353 and Vagrant 1.6.5

### ISSUE THREAD

**Issue by codeZeilen** [x-team/vdd#6]
The following appears when I simply try `vagrant up`:

    There is a syntax error in the following Vagrantfile. The syntax error message is reproduced below for convenience:

    vdd/Vagrantfile:45: syntax error, unexpected tIDENTIFIER, expecting keyword_end
     ...r"]["type"].present? vdd_config["synced_folder"]["type"] : "...
     ...                               ^
    vdd/Vagrantfile:45: syntax error, unexpected ':', expecting     keyword_end
     ...nfig["synced_folder"]["type"] : "rsync"
     ...                               ^                         ^

**Comment by flacoman91** [comment]
thanks for sharing this. I could not get it to work without the fix.

**Comment by thedamon** [comment]
same issue here. thanks for the fix

**Comment by geraldvillorente** [comment]
Merged the fix.
